// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztxjbuyobctacqblfbom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0eGpidXlvYmN0YWNxYmxmYm9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjExNzMsImV4cCI6MjA3MDMzNzE3M30.kYHD2L_BigHZ-muP4JgHaKWU9BF0Zq_BB8JnQ0XuzsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});